---
title: "Regression"
author: "Blain Morin and Matthew Pesavento"
date: "5/25/2021"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(tidyverse)
library(RSQLite)
library(lubridate)
library(stargazer)

```


```{r}

conn = dbConnect(RSQLite::SQLite(), "puco.db")

test = dbGetQuery(conn, "SELECT * FROM Responses WHERE ContractTerms in (3, 12, 24) AND refRateType = 'Fixed' and MeasurementText = 'kWh' AND refRateCode = 'Residential' ")

test1 = test %>%
  mutate(Offer_Date = substring(test$PublishDate, 1, 10)) %>%
  mutate(Offer_Date = ymd(Offer_Date))

AEP = test1 %>%
  filter(TerritoryName == "American Electric Power")

remove(test)

```

```{r, results='asis'}

AEP1 = AEP %>%
  mutate(Offer_Date = substring(AEP$PublishDate, 1, 10)) %>%
  mutate(ContractTerms = as.factor(ContractTerms)) %>%
  mutate(Offer_Date = ymd(Offer_Date)) %>%
  mutate(Utility_Price = 0) %>%
  mutate(Utility_Price = ifelse(Offer_Date >= ymd("2014-06-01"), 49.3385
, NA)) %>%
  mutate(Utility_Price = ifelse(Offer_Date >= ymd("2015-06-01"), 54.8702

, Utility_Price)) %>%
  mutate(Utility_Price = ifelse(Offer_Date >= ymd("2016-06-01"), 52.9831

, Utility_Price)) %>%
  mutate(Utility_Price = ifelse(Offer_Date >= ymd("2017-06-01"), 51.1387

, Utility_Price)) %>%
  mutate(Utility_Price = ifelse(Offer_Date >= ymd("2018-06-01"), 49.3497

, Utility_Price)) %>%
  mutate(Utility_Price = ifelse(Offer_Date >= ymd("2019-06-01"), 47.376

, Utility_Price)) %>%
  mutate(Utility_Price = ifelse(Offer_Date >= ymd("2020-06-01"), 42.1655

, Utility_Price))


AEP1 = AEP1 %>%
  filter(Price < 1) %>%
  mutate(Utility_Price == Utility_Price / 1000)

test3 = lm(Price ~ Utility_Price + ContractTerms, data = AEP1)

stargazer(test3, header = FALSE, digits = 6)



```
