---
title: "Price-to-Compare Electric Graphics"
author: "Blain Morin"
date: "6/29/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE)
library(tidyverse)
library(gridExtra)
library(kableExtra)
library(knitr)
library(lubridate)
library(plotly)
library(RSQLite)
library(RColorBrewer)
library(readr)

```


```{r}

conn = dbConnect(RSQLite::SQLite(), "puco.db")

test = dbGetQuery(conn, "SELECT * FROM Responses WHERE ContractTerms in (3, 12, 24) AND refRateType = 'Fixed' and MeasurementText = 'kWh' AND refRateCode = 'Residential' ")

dbDisconnect(conn)

```

# AEP-CSP

```{r, fig.height=8, fig.width=12}

AEP = test %>%
  mutate(Offer_Date = substring(test$PublishDate, 1, 10)) %>%
  mutate(Offer_Date = ymd(Offer_Date)) %>%
  mutate(ContractTerms = as.factor(ContractTerms)) %>%
  filter(TerritoryName == "American Electric Power")


PTC = read_csv("PTC.csv")

df = PTC %>%
  select(Date, AEPCSP) %>%
  mutate(Date = mdy(Date)) %>%
  mutate(matchdate = format(Date, "%m/%Y")) %>%
  select(matchdate, AEPCSP)

AEP = AEP %>%
  mutate(matchdate = format(Offer_Date, "%m/%Y"))


AEP = AEP %>% 
  left_join(df)

df2 = AEP %>%
  group_by(Offer_Date, ContractTerms) %>%
  summarize(Min = min(Price),
            "5%" = quantile(Price, probs = .05),
            q1 = quantile(Price, probs = .25),
            Mean = mean(Price),
            Median = median(Price),
            q3 = quantile(Price, probs = .75),
            Max = max(Price),
            PTC = mean(AEPCSP)/100) %>%
  gather(Offer, Price, Min:PTC) %>%
  filter(Price != 9999)

mycolors = brewer.pal(8, name = 'Spectral')
mycolors[5] = "purple"

df2$Offer = factor(df2$Offer, levels = c("Min", "5%", "q1", "Mean", "PTC", "Median", "q3", "Max"))

g = df2 %>%
  filter(Price < .1) %>%
  ggplot(aes(x = Offer_Date, y = Price)) +
  geom_line(aes(color = Offer)) +
  facet_wrap(~ContractTerms) +
  scale_x_date(date_minor_breaks = "1 year") +
  scale_color_manual(name = "Offer", values = mycolors) +
  theme_bw() +
  theme(strip.background =element_rect(fill="black")) +
  theme(strip.text = element_text(colour = 'white')) +
  xlab("Date") +
  ylab("kwh") +
  ggtitle("AEP-CSP Residential, With PTC")


ggplotly(g)

```

# AEP-OP

```{r, fig.height=8, fig.width=12}

AEP = test %>%
  mutate(Offer_Date = substring(test$PublishDate, 1, 10)) %>%
  mutate(Offer_Date = ymd(Offer_Date)) %>%
  mutate(ContractTerms = as.factor(ContractTerms)) %>%
  filter(TerritoryName == "American Electric Power")


PTC = read_csv("PTC.csv")

df = PTC %>%
  select(Date, AEPOP) %>%
  mutate(Date = mdy(Date)) %>%
  mutate(matchdate = format(Date, "%m/%Y")) %>%
  select(matchdate, AEPOP)

AEP = AEP %>%
  mutate(matchdate = format(Offer_Date, "%m/%Y"))


AEP = AEP %>% 
  left_join(df)

df2 = AEP %>%
  group_by(Offer_Date, ContractTerms) %>%
  summarize(Min = min(Price),
            "5%" = quantile(Price, probs = .05),
            q1 = quantile(Price, probs = .25),
            Mean = mean(Price),
            Median = median(Price),
            q3 = quantile(Price, probs = .75),
            Max = max(Price),
            PTC = mean(AEPOP)/100) %>%
  gather(Offer, Price, Min:PTC) %>%
  filter(Price != 9999)

mycolors = brewer.pal(8, name = 'Spectral')
mycolors[5] = "purple"

df2$Offer = factor(df2$Offer, levels = c("Min", "5%", "q1", "Mean", "PTC", "Median", "q3", "Max"))

g = df2 %>%
  filter(Price < .1) %>%
  ggplot(aes(x = Offer_Date, y = Price)) +
  geom_line(aes(color = Offer)) +
  facet_wrap(~ContractTerms) +
  scale_x_date(date_minor_breaks = "1 year") +
  scale_color_manual(name = "Offer", values = mycolors) +
  theme_bw() +
  theme(strip.background =element_rect(fill="black")) +
  theme(strip.text = element_text(colour = 'white')) +
  xlab("Date") +
  ylab("kwh") +
  ggtitle("AEP-OP Residential, With PTC")


ggplotly(g)

```

# FE-CEI

* Using the "Illuminating Company" as the territory for the CRES offers
* There are some high maximum values that pull the mean up, but get cut out of the y-axis bounds

```{r, fig.height=8, fig.width=12}

AEP = test %>%
  mutate(Offer_Date = substring(test$PublishDate, 1, 10)) %>%
  mutate(Offer_Date = ymd(Offer_Date)) %>%
  mutate(ContractTerms = as.factor(ContractTerms)) %>%
  filter(TerritoryName == "The Illuminating Company")


PTC = read_csv("PTC.csv")

df = PTC %>%
  select(Date, FECEI) %>%
  mutate(Date = mdy(Date)) %>%
  mutate(matchdate = format(Date, "%m/%Y")) %>%
  select(matchdate, FECEI)

AEP = AEP %>%
  mutate(matchdate = format(Offer_Date, "%m/%Y"))


AEP = AEP %>% 
  left_join(df)

df2 = AEP %>%
  group_by(Offer_Date, ContractTerms) %>%
  summarize(Min = min(Price),
            "5%" = quantile(Price, probs = .05),
            q1 = quantile(Price, probs = .25),
            Mean = mean(Price),
            Median = median(Price),
            q3 = quantile(Price, probs = .75),
            Max = max(Price),
            PTC = mean(FECEI)/100) %>%
  gather(Offer, Price, Min:PTC) %>%
  filter(Price != 9999)

mycolors = brewer.pal(8, name = 'Spectral')
mycolors[5] = "purple"

df2$Offer = factor(df2$Offer, levels = c("Min", "5%", "q1", "Mean", "PTC", "Median", "q3", "Max"))

g = df2 %>%
  filter(Price < .1) %>%
  ggplot(aes(x = Offer_Date, y = Price)) +
  geom_line(aes(color = Offer)) +
  facet_wrap(~ContractTerms) +
  scale_x_date(date_minor_breaks = "1 year") +
  scale_color_manual(name = "Offer", values = mycolors) +
  theme_bw() +
  theme(strip.background =element_rect(fill="black")) +
  theme(strip.text = element_text(colour = 'white')) +
  xlab("Date") +
  ylab("kwh") +
  ggtitle("FE-CEI Residential, With PTC")


ggplotly(g)

```

# FE-OE

```{r, fig.height=8, fig.width=12}

AEP = test %>%
  mutate(Offer_Date = substring(test$PublishDate, 1, 10)) %>%
  mutate(Offer_Date = ymd(Offer_Date)) %>%
  mutate(ContractTerms = as.factor(ContractTerms)) %>%
  filter(TerritoryName == "Ohio Edison")


PTC = read_csv("PTC.csv")

df = PTC %>%
  select(Date, FEOE) %>%
  mutate(Date = mdy(Date)) %>%
  mutate(matchdate = format(Date, "%m/%Y")) %>%
  select(matchdate, FEOE)

AEP = AEP %>%
  mutate(matchdate = format(Offer_Date, "%m/%Y"))


AEP = AEP %>% 
  left_join(df)

df2 = AEP %>%
  group_by(Offer_Date, ContractTerms) %>%
  summarize(Min = min(Price),
            "5%" = quantile(Price, probs = .05),
            q1 = quantile(Price, probs = .25),
            Mean = mean(Price),
            Median = median(Price),
            q3 = quantile(Price, probs = .75),
            Max = max(Price),
            PTC = mean(FEOE)/100) %>%
  gather(Offer, Price, Min:PTC) %>%
  filter(Price != 9999)

mycolors = brewer.pal(8, name = 'Spectral')
mycolors[5] = "purple"

df2$Offer = factor(df2$Offer, levels = c("Min", "5%", "q1", "Mean", "PTC", "Median", "q3", "Max"))

g = df2 %>%
  filter(Price < .1) %>%
  ggplot(aes(x = Offer_Date, y = Price)) +
  geom_line(aes(color = Offer)) +
  facet_wrap(~ContractTerms) +
  scale_x_date(date_minor_breaks = "1 year") +
  scale_color_manual(name = "Offer", values = mycolors) +
  theme_bw() +
  theme(strip.background =element_rect(fill="black")) +
  theme(strip.text = element_text(colour = 'white')) +
  xlab("Date") +
  ylab("kwh") +
  ggtitle("FE-OE Residential, With PTC")


ggplotly(g)


```


# FE-TE

```{r, fig.height=8, fig.width=12}

AEP = test %>%
  mutate(Offer_Date = substring(test$PublishDate, 1, 10)) %>%
  mutate(Offer_Date = ymd(Offer_Date)) %>%
  mutate(ContractTerms = as.factor(ContractTerms)) %>%
  filter(TerritoryName == "Toledo Edison")


PTC = read_csv("PTC.csv")

df = PTC %>%
  select(Date, FETE) %>%
  mutate(Date = mdy(Date)) %>%
  mutate(matchdate = format(Date, "%m/%Y")) %>%
  select(matchdate, FETE)

AEP = AEP %>%
  mutate(matchdate = format(Offer_Date, "%m/%Y"))


AEP = AEP %>% 
  left_join(df)

df2 = AEP %>%
  group_by(Offer_Date, ContractTerms) %>%
  summarize(Min = min(Price),
            "5%" = quantile(Price, probs = .05),
            q1 = quantile(Price, probs = .25),
            Mean = mean(Price),
            Median = median(Price),
            q3 = quantile(Price, probs = .75),
            Max = max(Price),
            PTC = mean(FETE)/100) %>%
  gather(Offer, Price, Min:PTC) %>%
  filter(Price != 9999)

mycolors = brewer.pal(8, name = 'Spectral')
mycolors[5] = "purple"

df2$Offer = factor(df2$Offer, levels = c("Min", "5%", "q1", "Mean", "PTC", "Median", "q3", "Max"))

g = df2 %>%
  filter(Price < .1) %>%
  ggplot(aes(x = Offer_Date, y = Price)) +
  geom_line(aes(color = Offer)) +
  facet_wrap(~ContractTerms) +
  scale_x_date(date_minor_breaks = "1 year") +
  scale_color_manual(name = "Offer", values = mycolors) +
  theme_bw() +
  theme(strip.background =element_rect(fill="black")) +
  theme(strip.text = element_text(colour = 'white')) +
  xlab("Date") +
  ylab("kwh") +
  ggtitle("FE-TE Residential, With PTC")


ggplotly(g)

```

# Duke

```{r, fig.height=8, fig.width=12}

AEP = test %>%
  mutate(Offer_Date = substring(test$PublishDate, 1, 10)) %>%
  mutate(Offer_Date = ymd(Offer_Date)) %>%
  mutate(ContractTerms = as.factor(ContractTerms)) %>%
  filter(TerritoryName == "Duke Energy Ohio")


PTC = read_csv("PTC.csv")

df = PTC %>%
  select(Date, DUKE) %>%
  mutate(Date = mdy(Date)) %>%
  mutate(matchdate = format(Date, "%m/%Y")) %>%
  select(matchdate, DUKE)

AEP = AEP %>%
  mutate(matchdate = format(Offer_Date, "%m/%Y"))


AEP = AEP %>% 
  left_join(df)

df2 = AEP %>%
  group_by(Offer_Date, ContractTerms) %>%
  summarize(Min = min(Price),
            "5%" = quantile(Price, probs = .05),
            q1 = quantile(Price, probs = .25),
            Mean = mean(Price),
            Median = median(Price),
            q3 = quantile(Price, probs = .75),
            Max = max(Price),
            PTC = mean(DUKE)/100) %>%
  gather(Offer, Price, Min:PTC) %>%
  filter(Price != 9999)

mycolors = brewer.pal(8, name = 'Spectral')
mycolors[5] = "purple"

df2$Offer = factor(df2$Offer, levels = c("Min", "5%", "q1", "Mean", "PTC", "Median", "q3", "Max"))

g = df2 %>%
  filter(Price < .1) %>%
  ggplot(aes(x = Offer_Date, y = Price)) +
  geom_line(aes(color = Offer)) +
  facet_wrap(~ContractTerms) +
  scale_x_date(date_minor_breaks = "1 year") +
  scale_color_manual(name = "Offer", values = mycolors) +
  theme_bw() +
  theme(strip.background =element_rect(fill="black")) +
  theme(strip.text = element_text(colour = 'white')) +
  xlab("Date") +
  ylab("kwh") +
  ggtitle("Duke Residential, With PTC")


ggplotly(g)

```

# DPL

```{r, fig.height=8, fig.width=12}

AEP = test %>%
  mutate(Offer_Date = substring(test$PublishDate, 1, 10)) %>%
  mutate(Offer_Date = ymd(Offer_Date)) %>%
  mutate(ContractTerms = as.factor(ContractTerms)) %>%
  filter(TerritoryName == "Dayton Power & Light")


PTC = read_csv("PTC.csv")

df = PTC %>%
  select(Date, DPL) %>%
  mutate(Date = mdy(Date)) %>%
  mutate(matchdate = format(Date, "%m/%Y")) %>%
  select(matchdate, DPL)

AEP = AEP %>%
  mutate(matchdate = format(Offer_Date, "%m/%Y"))


AEP = AEP %>% 
  left_join(df)

df2 = AEP %>%
  group_by(Offer_Date, ContractTerms) %>%
  summarize(Min = min(Price),
            "5%" = quantile(Price, probs = .05),
            q1 = quantile(Price, probs = .25),
            Mean = mean(Price),
            Median = median(Price),
            q3 = quantile(Price, probs = .75),
            Max = max(Price),
            PTC = mean(DPL)/100) %>%
  gather(Offer, Price, Min:PTC) %>%
  filter(Price != 9999)

mycolors = brewer.pal(8, name = 'Spectral')
mycolors[5] = "purple"

df2$Offer = factor(df2$Offer, levels = c("Min", "5%", "q1", "Mean", "PTC", "Median", "q3", "Max"))

g = df2 %>%
  filter(Price < .1) %>%
  ggplot(aes(x = Offer_Date, y = Price)) +
  geom_line(aes(color = Offer)) +
  facet_wrap(~ContractTerms) +
  scale_x_date(date_minor_breaks = "1 year") +
  scale_color_manual(name = "Offer", values = mycolors) +
  theme_bw() +
  theme(strip.background =element_rect(fill="black")) +
  theme(strip.text = element_text(colour = 'white')) +
  xlab("Date") +
  ylab("kwh") +
  ggtitle("Dayton Power and Light Residential, With PTC")


ggplotly(g)

```


